/**
 * Client for the Kessler API.
 *
 * The API holds the HydraDB bearer token and owns the Cypher; this file only
 * shapes requests and surfaces failures honestly. A 502 means the graph database
 * is down, and the UI says exactly that rather than showing an empty result —
 * "no paths found" and "could not ask" are completely different answers to a
 * security question.
 */

const BASE = import.meta.env.VITE_API_URL ?? 'http://127.0.0.1:8787';

export type ScanPath = {
  nodes: string[];
  depth: number;
};

export type Coverage_ = {
  total: number;
  inGraph: number;
  missing: string[];
  missingCount: number;
};

export type Ingested = {
  versionsWritten?: number;
  edgesWritten?: number;
  alreadyPresent?: number;
  ms?: number;
  skipped?: string;
};

export type ScanResult = {
  compromised: string;
  sources: number;
  packages: number;
  devSkipped: number;
  exposedCount: number;
  maxDepth: number;
  elapsedMs: number;
  coverage: Coverage_;
  ingested: Ingested | null;
  paths: ScanPath[];
};

/** The bundled example — a real lockfile, generated by npm, nothing doctored. */
export const EXAMPLE = {
  lockfile: '/demo-lockfile.json',
  target: 'function-bind@1.1.2',
  label: 'kessler-demo-project',
};

export async function loadExampleLockfile(): Promise<string> {
  const res = await fetch(EXAMPLE.lockfile);
  if (!res.ok) throw new ApiError('Could not load the example lockfile.', res.status, 'unknown');
  return res.text();
}

export type Incident = {
  pkg: string;
  version: string;
  key: string;
  date: string;
  label: string;
  summary: string;
  inGraph: boolean;
};

export type ChokePoint = {
  target: string;
  reachedBy: number;
  paths: number;
  maxDepth: number;
  deepPaths: number;
  score: number;
  deepest: ScanPath | null;
};

export function incidents(): Promise<{ incidents: Incident[] }> {
  return request('/incidents');
}

/**
 * "What in my tree would hurt most if it were compromised" — the question you
 * can ask when no advisory has landed yet.
 */
export function chokepoints(lockfile: string): Promise<{
  totalVersions: number;
  chokepoints: ChokePoint[];
}> {
  return request('/chokepoints', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ lockfile }),
  });
}

export type Coverage = {
  packages: number;
  maxDepth: number;
};

export class ApiError extends Error {
  constructor(
    message: string,
    readonly status: number | null,
    readonly kind: 'offline' | 'database' | 'input' | 'notfound' | 'unknown'
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${BASE}${path}`, init);
  } catch {
    throw new ApiError(`Cannot reach the Kessler API at ${BASE}.`, null, 'offline');
  }

  const text = await res.text();
  let body: unknown = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    /* fall through to status-based handling */
  }

  if (!res.ok) {
    const message =
      (body as { error?: string } | null)?.error ?? `Request failed (${res.status}).`;
    throw new ApiError(
      message,
      res.status,
      res.status === 502 ? 'database' : res.status === 404 ? 'notfound' : res.status === 400 ? 'input' : 'unknown'
    );
  }
  return body as T;
}

export function scan(lockfile: string, compromised: string): Promise<ScanResult> {
  return request<ScanResult>('/scan', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ lockfile, compromised }),
  });
}

export function coverage(): Promise<Coverage> {
  return request<Coverage>('/coverage');
}

export function health(): Promise<{ ok: boolean; hydradb: string }> {
  return request('/health');
}
